language: cpp

sudo: true

os:
    - linux
    # - osx

compiler:
    # - clang
    - gcc

env:
    - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"

# matrix:
#     - exclude:
#         - os: osx
#           compiler: gcc
#     - allow_failures:
#         - os: osx
#         - compiler: clang

addons:
    apt:
        sources:
            - boost-latest
            # - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
            # - beineri/opt-qt487
        packages:
            # - clang-3.5
            - doxygen
            - g++-4.9
            - gdal-bin
            - imagemagick
            - libgdal-dev
            - libgeos++-dev
            - libboost1.55-all-dev
            # - libqt4-dev
            # - libqt4-dev-bin
            # - libqwt-dev
            - libxml2-dev
            - libxslt1-dev
            - python-dev
            # - python-docopt
            - python-numpy
            - python-virtualenv
            # - opt-qt4-qmake
            # - opt-qt4-dev-tools  # source /opt/qt-4.8/bin/qt-4.8-env.sh
            # - opt-libqt4-dev  # source /opt/qt-4.8/bin/qt-4.8-env.sh
            # - xsdcxx
            - xsltproc
            # - libc++-dev

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt487 -y
    - sudo apt-get update -qq

    # Update CMake.
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz

    # We need to patch xsd because of:
    # http://www.codesynthesis.com/pipermail/xsd-users/2014-February/004196.html
    - wget http://www.codesynthesis.com/download/xsd/3.3/linux-gnu/x86_64/xsd-3.3.0-x86_64-linux-gnu.tar.bz2
    # - wget http://www.codesynthesis.com/download/xsd/3.3/linux-gnu/x86_64/xsd_3.3.0-1_amd64.deb
    - wget http://codesynthesis.com/~boris/tmp/xsd/xsd-3.3.0-gcc-4.7-clang.patch
    - if [ "$CC" = "clang" ]; then export CC="clang-3.5" CXX="clang++-3.5"; fi
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CXX="g++-4.9"; fi

    # Travis doesn't have
    # - PCRaster's raster format library
    # - Qwt library
    # We build and install those ourselves using Peacock.
    - git clone --recursive https://github.com/geoneric/peacock.git

install:
    - set -e

    - cd $TRAVIS_BUILD_DIR
    # - virtualenv --system-site-packages my_python
    # - source my_python/bin/activate
    - pip install --upgrade docopt
    - pip install --upgrade sphinx
    # - pip install numpy

    - sudo apt-get install opt-qt4-qmake opt-qt4-dev-tools
    - export PATH=/opt/qt-4.8/bin:$PATH
    - cat /opt/qt-4.8/bin/qt-4.8-env.sh

    - mkdir $TRAVIS_BUILD_DIR/local

    - cd $TRAVIS_BUILD_DIR/local
    - tar zxf ../cmake-3.2.3-Linux-x86_64.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/local/cmake-3.2.3-Linux-x86_64/bin:$PATH

    - cd $TRAVIS_BUILD_DIR/local
    - tar jxf ../xsd-3.3.0-x86_64-linux-gnu.tar.bz2
    - cd xsd-3.3.0-x86_64-linux-gnu
    - patch -p1 < ../../xsd-3.3.0-gcc-4.7-clang.patch
    - export PATH=$TRAVIS_BUILD_DIR/local/xsd-3.3.0-x86_64-linux-gnu/bin:$PATH
    # - sudo dpkg --install ./xsd_3.3.0-1_amd64.deb

    - cd $TRAVIS_BUILD_DIR/peacock
    - mkdir build
    - cd build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -Dpeacock_prefix=$TRAVIS_BUILD_DIR/local -Dbuild_pcraster_raster_format=true -Dpcraster_raster_format_version=1.3.1 -Dbuild_qwt=true -Dqwt_version=6.0.2 ..
      # -Dbuild_qt=true -Dqt_version=4.8.6 
    - cmake --build . --target all

before_script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DPEACOCK_PREFIX:PATH=$TRAVIS_BUILD_DIR/local -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DPCRASTER_BUILD_TEST:BOOL=TRUE ..

script:
    - set -e  # Don't run the tests if the build fails.
    # - source my_python/bin/activate
    - cd $TRAVIS_BUILD_DIR/build

    # Split the build, 'make all' takes > 50 minutes, which is not allowed.
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target pcraster_aguila
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target test
    - cd ..

notifications:
    email:
        - k.dejong1@uu.nl
        # - o.schmitz@uu.nl
