language: cpp

sudo: true

os:
    - linux
    # - osx

compiler:
    # - clang
    - gcc

env:
    - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"

# matrix:
#     - exclude:
#         - os: osx
#           compiler: gcc
#     - allow_failures:
#         - os: osx
#         - compiler: clang

# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
# https://github.com/hicknhack-software/Twofold-Qt/blob/develop/.travis.yml
addons:
    apt:
        sources:
            - boost-latest
            # - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
            - beineri/opt-qt487
        packages:
            # - clang-3.5
            - g++-4.9
            - gdal-bin
            - imagemagick
            - libgdal-dev
            - libgeos++-dev
            - libboost1.55-all-dev
            # - libqt4-dev
            # - libqt4-dev-bin
            # - libqwt-dev
            - libxml2-dev
            - libxslt1-dev
            - python-dev
            # - opt-qt4-qmake
            # - opt-qt4-dev-tools  # source /opt/qt-4.8/bin/qt-4.8-env.sh
            # - opt-libqt4-dev  # source /opt/qt-4.8/bin/qt-4.8-env.sh
            - xsdcxx
            - xsltproc
            # - libc++-dev

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt487 -y
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - if [ "$CC" = "clang" ]; then export CC="clang-3.5" CXX="clang++-3.5"; fi
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CXX="g++-4.9"; fi

    # Travis doesn't have
    # - PCRaster's raster format library
    # - Qwt library
    # We build and install those ourselves using Peacock.
    - git clone --recursive https://github.com/geoneric/peacock.git

install:
    - set -e
    # - sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools; source /opt/qt-4.8/bin/qt-487-env.sh
    # - sudo apt-get install -qq opt-libqt4-dev  # ; source /opt/qt-4.8/bin/qt-487-env.sh
    #                            opt-libqt4-dev
    # - sudo apt-get install -qq qt48base qt48script  # ; source /opt/qt48/bin/qt48-env.sh
    # - sudo apt-get install -qq opt-libqt4-dev opt-libqt4-dev-bin
    # - source /opt/qt48/bin/qt48-env.sh
    - sudo apt-get install opt-qt4-qmake opt-qt4-dev-tools
    - ls /opt
    - ls /opt/qt-4.8
    - ls /opt/qt-4.8/bin
    - source /opt/qt-4.8/bin/qt-4.8-env.sh

    - mkdir $TRAVIS_BUILD_DIR/local

    - cd $TRAVIS_BUILD_DIR/local
    - tar zxf ../cmake-3.2.3-Linux-x86_64.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/local/cmake-3.2.3-Linux-x86_64/bin:$PATH

    - cd $TRAVIS_BUILD_DIR/peacock
    - mkdir build
    - cd build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -Dpeacock_prefix=$TRAVIS_BUILD_DIR/local -Dbuild_pcraster_raster_format=true -Dpcraster_raster_format_version=1.3.1 -Dbuild_qwt=true -Dqwt_version=6.0.2 ..
      # -Dbuild_qt=true -Dqt_version=4.8.6 
    - cmake --build . --target all

before_script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DPEACOCK_PREFIX:PATH=$TRAVIS_BUILD_DIR/local -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DPCRASTER_BUILD_TEST:BOOL=TRUE ..

script:
    - set -e  # Don't run the tests if the build fails.
    - cd $TRAVIS_BUILD_DIR/build
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target test
    - cd ..

notifications:
    email:
        - k.dejong1@uu.nl
        # - o.schmitz@uu.nl
