language: cpp

sudo: true

os:
    - linux
    # - osx

compiler:
    # - clang
    - gcc

env:
    # - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    # TODO build is taking too long, split even more, see script section
    - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"

# matrix:
#     - exclude:
#         - os: osx
#           compiler: gcc
#     - allow_failures:
#         - os: osx
#         - compiler: clang

addons:
    apt:
        sources:
            - boost-latest
            # - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
        packages:
            # - clang-3.5
            - g++-4.9
            - libboost1.55-all-dev
            - libxerces-c-dev
            - libxml2-dev
            - libxslt1-dev
            - python-dev
            - python-gdal
            - python-numpy
            - python-virtualenv
            - xsltproc
            # - libc++-dev
            # - gdal-bin # 02/2016 travis vm currently installs v1.x
            # - libgdal-dev
            # - doxygen
            # - graphviz
            # - imagemagick

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562 -y
    - sudo apt-get update -qq

    # - sudo add-apt-repository ppa:ubuntugis/ubuntugis-testing -y
    # - sudo apt-get update -q
    # - sudo apt-get install gdal-bin libgdal-dev

    # Update CMake.
    - wget --no-check-certificate http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz

    # We need to patch xsd because of:
    # http://www.codesynthesis.com/pipermail/xsd-users/2014-February/004196.html
    - wget --no-check-certificate http://www.codesynthesis.com/download/xsd/3.3/linux-gnu/x86_64/xsd-3.3.0-x86_64-linux-gnu.tar.bz2
    - wget --no-check-certificate http://codesynthesis.com/~boris/tmp/xsd/xsd-3.3.0-gcc-4.7-clang.patch
    - if [ "$CC" = "clang" ]; then export CC="clang-3.5" CXX="clang++-3.5"; fi
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CXX="g++-4.9"; fi

    # Travis doesn't have
    # - PCRaster's raster format library
    # - Qwt library
    # We build and install those ourselves using Peacock.
    - git clone --recursive https://github.com/geoneric/peacock.git

install:
    - set -e

    - cd $TRAVIS_BUILD_DIR
    - sudo pip install --upgrade pip
    - sudo pip install --upgrade docopt
    - sudo pip install --upgrade sphinx
    - sudo pip install pillow

    # - sudo apt-get install opt-qt4-qmake opt-qt4-dev-tools
    - sudo apt-get install qt56base
    - export PATH=/opt/qt56/bin:$PATH
    # - cat /opt/qt-4.8/bin/qt-4.8-env.sh

    - mkdir $TRAVIS_BUILD_DIR/local

    - cd $TRAVIS_BUILD_DIR/local
    - tar zxf ../cmake-3.2.3-Linux-x86_64.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/local/cmake-3.2.3-Linux-x86_64/bin:$PATH

    - cd $TRAVIS_BUILD_DIR/local
    - tar jxf ../xsd-3.3.0-x86_64-linux-gnu.tar.bz2
    - cd xsd-3.3.0-x86_64-linux-gnu
    - patch -p1 < ../../xsd-3.3.0-gcc-4.7-clang.patch
    - export PATH=$TRAVIS_BUILD_DIR/local/xsd-3.3.0-x86_64-linux-gnu/bin:$PATH

    - cd $TRAVIS_BUILD_DIR/peacock
    - export MAKEFLAGS='-j2'
    - mkdir build
    - cd build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -Dpeacock_prefix=$TRAVIS_BUILD_DIR/local -Dbuild_pcraster_raster_format=true -Dpcraster_raster_format_version=1.3.1 -Dbuild_qwt=true -Dqwt_version=6.1.2 -Dbuild_gdal=true -Dgdal_version=2.0.1 -Dbuild_fern=true -Dfern_git_repository=https://github.com/geoneric/fern.git -Dfern_git_tag=f67bdc78b21932025dd85b085c9bcf3464979de9 -Dfern_build_fern_algorithm=true -Dfern_build_fern_documentation=false -Dfern_build_fern_test=false ..
    - cmake --build . --target all

before_script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DPEACOCK_PREFIX:PATH=$TRAVIS_BUILD_DIR/local -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DPCRASTER_WITH_PYTHON_MULTICORE:BOOL=TRUE -DPCRASTER_BUILD_TEST:BOOL=TRUE ..

script:
    - set -e  # Don't run the tests if the build fails.
    - cd $TRAVIS_BUILD_DIR/build
    - export MAKEFLAGS='-j2'
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all

    # own GDAL 2.x library needs to be found to execute unit tests
    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/local/linux/linux/gcc-4/x86_64/lib
    - export MAKEFLAGS='-j1'
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target test
    - cd ..

notifications:
    email:
        - k.dejong1@uu.nl
        - o.schmitz@uu.nl
