language: cpp

dist: trusty

sudo: required

notifications:
    email:
        on_success: change
        on_failure: always

branches:
    only:
        - gh222

#os:
    #- linux
    ## - osx

#compiler:
    ## - clang
    #- gcc

#env:
    ## - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    ## TODO build is taking too long, split even more, see script section
    #- TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"


# matrix:
#     - exclude:
#         - os: osx
#           compiler: gcc
#     - allow_failures:
#         - os: osx
#         - compiler: clang

matrix:
  include:
    ## Linux, test the oldest gcc version we support, debug build
    #- name: "Linux, gcc 4.9 debug"
      #os: linux
      #addons:
        #apt:
          #sources:
            #- ubuntu-toolchain-r-test
          #packages:
            #- g++-4.9
      #env:
         #- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         #- TRAVIS_BUILD_TYPE=Debug
         #- TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
      #before_install:
         #- ./environment/travis/linux/before_install.sh
      #install:
         #- source environment/travis/linux/install.sh
      #before_script:
         #- ./environment/travis/linux/before_script.sh


    # Linux, test the latest gcc version, release build
    - name: "Linux, gcc 8 release"
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - TRAVIS_BUILD_TYPE=Debug
        - TRAVIS_CMAKE_GENERATOR="Unix Makefiles"

      before_install:
        - ./environment/travis/linux/before_install.sh

      install:
        #- eval "${MATRIX_EVAL}"
        - ./environment/travis/linux/install.sh
        - export PATH=$TRAVIS_BUILD_DIR/local/cmake-3.12.1-Linux-x86_64/bin:$PATH
        - export PATH=/opt/qt56/bin:$PATH

      before_script:
        #- eval "${MATRIX_EVAL}"
        - ./environment/travis/linux/before_script.sh

      script:
        - set -e  # Don't run the tests if the build fails.
        - cd $TRAVIS_BUILD_DIR/build
#    - export MAKEFLAGS='-j2'
        - python -c "import numpy as n; print(n.__version__); print(n.get_include());"
#    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all -- -j2

#    - export MAKEFLAGS='-j1'
#    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target test
        - cd ..



    ## macOS, release build
    #- name: "macOS, gcc7 release"
      #os: osx
      #osx_image: xcode9.4
      #before_install:
      ##- brew update
      #- clang --version
      #- clang++ --version
      #- cmake --version
      ##- brew install --with-toolchain llvm
      #- brew install boost boost-python qt5 qwt xerces-c gdal ncurses
      ##- gcc --version
      ##- g++ --version


