language: cpp

sudo: false

os:
    - linux
    # - osx

compiler:
    # - clang
    - gcc

env:
    - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"

# matrix:
#     - exclude:
#         - os: osx
#           compiler: gcc
#     - allow_failures:
#         - os: osx
#         - compiler: clang

# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
addons:
    apt:
        sources:
            - boost-latest
            # - llvm-toolchain-precise-3.5
            - ubuntu-toolchain-r-test
        packages:
            # - clang-3.5
            - g++-4.9
            - gdal-bin
            - imagemagick
            - libgdal-dev
            - libgeos++-dev
            - libboost1.55-all-dev
            - libqt4-dev
            - libqt4-dev-bin
            - libqwt-dev
            - libxml2-dev
            - libxslt1-dev
            - python-dev
            - xsltproc
            # - libc++-dev

before_install:
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - if [ "$CC" = "clang" ]; then export CC="clang-3.5" CXX="clang++-3.5"; fi
    - if [ "$CC" = "gcc" ]; then export CC="gcc-4.9" CXX="g++-4.9"; fi
    - git clone git://git.code.sf.net/p/pcraster/rasterformat pcraster_raster_format

install:
    - mkdir $TRAVIS_BUILD_DIR/local

    - cd $TRAVIS_BUILD_DIR/local
    - tar zxf ../cmake-3.2.3-Linux-x86_64.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/local/cmake-3.2.3-Linux-x86_64/bin:$PATH

    - cd $TRAVIS_BUILD_DIR/pcraster_raster_format
    - mkdir build
    - cd build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_INSTALL_PREFIX:PATH=$TRAVIS_BUILD_DIR/local ..
    - cmake --build . --target all
    - cmake --build . --target install

before_script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_PREFIX_PATH:PATH=$TRAVIS_BUILD_DIR/local -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DPCRASTER_BUILD_TEST:BOOL=TRUE ..

script:
    - cd $TRAVIS_BUILD_DIR/build
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target test
    - cd ..


# notifications:
#     email:
#         - k.dejong1@uu.nl
#         - o.schmitz@uu.nl
